### ISSUE TITLE
verifyimports seem to fail on ewasm-rust-api generated code

### ISSUE THREAD

**Issue by axic** [wasmx/wasm-chisel#57] opened 2018-12-21 23:28 UTC
All of the precompiles fail with something similar:
```
$ target/debug/chisel sentinel ewasm_precompile_bls12pairing.wasm 
========== SENTINEL ==========
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 5', libchisel/src/verifyimports.rs:507:38
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jakelang** [comment] 2018-12-21 23:31
Duplicate of #47

**Closed** 2018-12-21 23:40 UTC
Labels: bug, duplicate
